#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

xinghan = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABVtJ"
    "REFUWIW9l22IXVcVht93nTPDJE7nnjOQmOSeyY0xltIM6cz0GmqsJQE/QE2KJPYDqiV/xCCl"
    "xKKlYChSRPKjBIRUaltpkKCtWqS2Sr+sVltqTeaehJtQJFYS782EDpkvpunk3rvX64/m+iNJ"
    "J3Olk/fXZu991nrO2muvxSauoEo6cFaubqPdOTR16rkr7e9UdqUNkdlnSbwohvs/aucfClBJ"
    "sh/k16y6FgA2nD35NoXnAa66agAihz2Kdvxvgv7uYjgHgPhyk4TWgPZCJSne5c43CZqEc4sB"
    "cEkEBBjANVTrNMgvGFFx+S7S564KwLG+LCHQFzw6A8c6GHoFGxS4KACXHMFcFHpNsaELpxn4"
    "qICXab5ZwtWJQOTdRsIpXi/oXggbIW4i+fZiAFwSgQiyABg9PArxPhquA/BKqxmeXHSA0f7i"
    "jhDCNwA+0NXVeGRwfHy2khb/QXEU1+AcZi/sS4pPGO00xHGnf5pADcJ7URT9JoTWPsCqjMNj"
    "ana9mySYe28yLF0/U5s6tqy0vNnA3Pmoy7vVGKTC9hgAKoXiZpndi+BVIL57ePLkVBuKYhlk"
    "OX4/zgB8BQBI3uXksEl3E3CIXxX9/mYIyyNwk6gGmnYzGe6bnNY/SVuRF4oPqNHaTmBDj7wG"
    "ABJbVkmyh2X4LYDqyHR9z/D0B84PrVy5tJJm3xd0AgpbW0taXweAf5dKPXCM0sMIiI10OwB4"
    "fzOORwkM0rSeQhnU5yQ8C/AlmZ8h7Xsk1oE2a849kGIYjjFPB5pwv31ouv5MpVBKFKlM+VY4"
    "Pk/jnxy6mR5taYMdTYobHNFqyWOACRByRjYSR+efboQlN9H9OkhVWdSIjRNSa1bioOB9cGvI"
    "1JierL+YFlbf4hZ6OJoWv2zAfoHvSLiWxFtw/h5UJuBrBEYEPD0yVbv91Qs5swVoXZxMb/av"
    "67tp4sTM/52Nr5ZKPbpwLSuFUlJJBv6Yp5kqhez9w33ZOgDI0+LBPMlev+RbIM6TrK4FdNcF"
    "S4DlSfZCng481J47kgxsy5NMAFBJV38rTwcOtqNSSbO/5mk22KkfzrdYSQeOEPoxHEud1hsL"
    "zwWEfcPT9VsrhVIC+n8IPCJqBRy3wdhN+e6hqfpPFgpw2W7Yljl3ivq7TA7oD4LySNHuQytX"
    "LsVcOECxR9I3QZygsScEfao/jWuYms/qRT7mW3RwguCDRnzS3H/h0P4WWmvLY2PnBN8r+csg"
    "3qCwFq5TN87UTnzi5MmOesa8RyDACHh7nCfZUyC2Cb6Fih4G/G8Cv2vgIYAPSa3a8PTpvBOA"
    "eSPQdt4ed3Wd30ngOBH9lOAvRZw18h2nyg7fStjr1b6s/yMDuFiD4+OzLu6j+w9F/zjF2OWv"
    "UWiQfAVEPj5T66gWdHxvjbrHjT0Cvw2xRmEjyR5ITxm063JFaj7Newsu1pEku8UBo3M5TG/A"
    "tIfOFQIA8FcbpmpHO7EHdBiBQO0EsQvEeg/YTfJHIBoEQOiOTp13BPBBxeOa4YnaWxLOxBE2"
    "y/EYgESAC3p8tFDckX9s7fJFAUgKpczAC31cByYma08C+jlIUJol7Ytm9mt1NQ9Xly3rXajd"
    "BecALfQKmDicZncY8Jk0zbbJtUIQADxO5/Okeh2ezMWxX8leWx3lAIWyifvpigU8y4jfAThr"
    "CgdhvldUo2FLflceG1vwI2bBETCLWsFDGeA9Q1P1n1VxfXezMPMXUHtvmB4brfZlX2pF+FeP"
    "n+/O0+y4gOOETkFsBuDPN07VXrvsTy0UQIAd7S+uumGiXqv2Zf2tiE84vDo8WX+wXTErhVIC"
    "022E3ylpE2HdkG8fmq4/82F2/wt9vXqV6gcY2QAAAABJRU5ErkJggg==")

